### ISSUE TITLE
Humongous arrows in latest build

### ISSUE THREAD

**Issue by LordFarin** [Benjol/SE-AutoReviewComments#100]
![image](https://cloud.githubusercontent.com/assets/794170/7667567/072c2e90-fc0d-11e4-853b-d671f84093db.png)

The latest build introduces these fantastic arrows which make the extension border line unusable. They are present whether or not the "show/hide desc" option is used.

Please fix this ASAP.

I'm using Comodo Dragon browser, which for practically all purposes can be considered equal to Google Chrome. I'm on Windows 7 x64, should it matter.

**Comment by Benjol** [comment]
Practically all purposes except this apparently :)
Just out of curiosity, have you tried it in Chrome. Also, which site is this on?
(Normally those arrows should only appear on hover)

Ben

-----Original Message-----

**Comment by LordFarin** [comment]
It's the same in Chrome. I'm on Maths.SE (http://math.stackexchange.com/).

It might have to do with a recent complete overhaul of the UI, see http://meta.math.stackexchange.com/q/20047/43351.

Thanks for looking into it.

**Comment by oliversalzburg** [comment]
Yeah, it's caused by recent CSS updates of buttons. :\

**Comment by Benjol** [comment]
@LordFarin, there is a fix from Oliver, but no release to go with it at present. Do you have the wherewithall to build and check?

**Comment by LordFarin** [comment]
@Benjol Unfortunately, no. However, I do have some past experience with Git so with some quick pointers I should be able to manage.

**Comment by oliversalzburg** [comment]
@LordFarin https://github.com/Benjol/SE-AutoReviewComments/wiki/Building should get you started :)

**Comment by LordFarin** [comment]
I managed to do it. It now looks like this:

![image](https://cloud.githubusercontent.com/assets/794170/7689954/4e61ab74-fdb0-11e4-84ec-1d01406d5b1d.png)
![image](https://cloud.githubusercontent.com/assets/794170/7689964/5e44b0b8-fdb0-11e4-965c-8c4d779ef992.png)

That is much better, but there is still something strange going on with the arrow when the comment is still folded.

You can also see the translucent arrow of the top comment, which also seems unintended.

**Comment by oliversalzburg** [comment]
@LordFarin Yeah, that's what I was seeing as well. I wanted to leave it there like that to give users a hint that there is something to interact with.

If you have any suggestions on how to improve it, I'm all ears :)

**Comment by LordFarin** [comment]
What I would do (if it's possible) is the following:

1. Scale the arrow so that it fits the vertical space used by the folded/unfolded comment.
2. Always show the arrow to the right on hover of the comment (instead of only when you hover all the way to the right).

This should fix the translucent arrow overflow and IMO it would also make the interface more intuitive.
I hope it is clear what I envisage.

**Comment by oliversalzburg** [comment]
@LordFarin I implemented your second suggestion. Scaling the height of the arrow wouldn't be very easy.

I'll submit a new PR.

**Comment by bjb568** [comment]
Removing these:

    height:100%;margin:0;font-size:300%;color:transparent;background-color:transparent;border:0;transition:.3s;text-shadow:0 0 1px #fff;cursor:pointer

makes it usable. That's how I'm modding it indefinitely, until pushing the update button doesn't move my cheese like that o_o

**Comment by oliversalzburg** [comment]
@bjb568 Humm, yeah, that doesn't look too bad either. Feels more in-tune with the overall UX. I might give it another do-over.

I've never heard the phrase "move my cheese" before btw. I like it :D

**Comment by Benjol** [comment]
Personally I prefer the translucent until hover, but I'll take whatever you PR.

@oliversalzburg: http://en.wikipedia.org/wiki/Who_Moved_My_Cheese%3F

You probably have seen it before, just not noticed (http://meta.stackexchange.com/search?q=cheese+moved)

**Comment by oliversalzburg** [comment]
@Benjol I would recommend merging #102 for now and pushing a release, as the current version is hardly usable.

Other changes would probably come later on.

And thanks for the cheese moving insights ;D
