### ISSUE TITLE
Help and Improvement que

### ISSUE THREAD

**Issue by humbleRumble** [Benjol/SE-AutoReviewComments#103]
Could this also work with the `Explain your edit in a comment` section of the `Help and Improvement` que? This would be helpful as I find myself copy and pasting comments.

**Comment by Benjol** [comment]
@Oliver, as master of the multi-targeting code, what do you think?

-----Original Message-----

**Comment by oliversalzburg** [comment]
Surely a must-have. I'll try to take care of it ASAP.

**Comment by humbleRumble** [comment]
Thanks guys.

**Comment by oliversalzburg** [comment]
I noted that there are more cases in review queues where the comments are not available. Like when you edit a question in the Close Votes queue, you can provide an edit summary, something that is supported in other placed on the site.

I'll look into supporting that as well.
