### ISSUE TITLE
Comment's Markdown is messed up when inserting

### ISSUE THREAD

**Issue by LordFarin** [Benjol/SE-AutoReviewComments#109]
I have the following comment:

```
###[Q] Informative title
Please, try to make the titles of your questions more informative. E.g., *Why does $a<b$ imply $a+c<b+c$?* is much more useful for other users than *A question about inequality.* From [How can I ask a good question?](http://meta.math.stackexchange.com/a/589/): *Make your title as descriptive as possible. In many cases one can actually phrase the title as the question, at least in such a way so as to be comprehensible to an expert reader.* You can find more tips for choosing a good title [here](http://meta.math.stackexchange.com/a/10144/).
```

which when double-clicking in the selection for editing, or when inserting, shows as:

```
Please, try to make the titles of your questions more informative. E.g., *Why does $a<b$ imply="" $a+c<b+c$?<="" em=""> is much more useful for other users than <em>A question about inequality.* From [How can I ask a good question?](http://meta.math.stackexchange.com/a/589/): *Make your title as descriptive as possible. In many cases one can actually phrase the title as the question, at least in such a way so as to be comprehensible to an expert reader.* You can find more tips for choosing a good title [here](http://meta.math.stackexchange.com/a/10144/).</b$></em>
```

I'm sure you see the nonsensical gibberish that is being produced instead of a plaintext copy of what I put in. 

I don't care about fancy previews involving URL and Markdown parsing if they screw up the insertion of the actual comment. Please get this fixed.

FYI, I'm using Google Chrome and Comodo Dragon. The ID of SE-ARC is mentioned as `bcfoamnigomkoaaiceppbbdlembpeejc`, should it help.

**Comment by Benjol** [comment]
Someone more acerbic than I might remark that what you put in is pretty close to gibberish as well.

 

I’ll see what I can do.

 

Serf

**Comment by oliversalzburg** [comment]
I guess, the problematic bit boils down to `*Why does $a<b$ imply $a+c<b+c$?*`

**Comment by LordFarin** [comment]
@Benjol I'm sorry for my rude tone. I should've realised that you are maintaining ARC as a service to the community and shouldn't have phrased my report in such an arrogant and demanding way. I duly apologise :(.

**Comment by Benjol** [comment]
And I am sorry in turn. I should have put a smiley on the end. I was just mildly amused by the juxtaposition of the tone and the ‘Lord’ in your username J

**Comment by Benjol** [comment]
I suspect that it’s something to do with having an open AND closing tag <  >

I’ll have a look tomorrow.

**Comment by oliversalzburg** [comment]
It's actually not that we're doing too much, we just don't replace `<` and `>` with their respective HTML entities when [calling `ul.append()`](https://github.com/Benjol/SE-AutoReviewComments/blob/devel/src/autoreviewcomments.user.js#L348). jQuery then thinks they are HTML tags.

**Comment by Benjol** [comment]
@oliversalzburg, unfortunately same code gives different symptoms in different places. replacing `<` with `&lt;` in `markDownToHtml` fixes the preview problem, but then you get `&lt;` instead of `<` when the comment is inserted.

(Also, as an aside, I noticed that if you do double-click-to-edit then save, it 'breaks' the quick insert arrow)

**Comment by Benjol** [comment]
@oliversalzburg, we could always transform `&lt;` into `<` when doing `htmlToMarkDown`, but then we'll get people who *want* `&lt;` complaining... 

So I'm a bit stuck right now...

**Comment by oliversalzburg** [comment]
@Benjol Well, `&lt;` has to be replaced by `&amp;lt;` ;) We should probably construct the HTML nodes separately, then set the text content with http://api.jquery.com/text/

**Comment by Blacksilver42** [comment]
Pls fix I like putting hearts in my comments.

A Minimal example that reproduces the problem, for reference:

> Try making this into an [mcve], please! <3

**Comment by oliversalzburg** [comment]
If someone could give this a thorough testing before the next release, that'd be great ;D

**Comment by makyen** [comment]
First: Sorry, I've never gotten around to recreating the build environment for this script. Thus, I've never back-ported any changes I've made to my personal copy into something suitable for a PR here.

The solution appears complex and limited to a small set of HTML entities.

I've just been using:

    function htmlToMarkDown(html) {
      markdown = html.replace(/<a href="(.+?)">(.+?)<\/a>/g, '[$2]($1)').replace(/&amp;/g, '&');
      markdown = markdown.replace(/<em>(.+?)<\/em>/g, '*$1*').replace(/<strong>(.+?)<\/strong>/g, '**$1**');
      //Still have HTML entities. Convert them using a <textarea>.
      //Ref: https://stackoverflow.com/a/7394787/ and https://stackoverflow.com/a/1395954/
      var textarea = document.createElement('textarea');
      textarea.innerHTML = markdown;
      return textarea.value;
    }

**Comment by oliversalzburg** [comment]
@makyen Does this also take the conversions during import/export into account?

I've previously planned for wider support, but I ran into issues during the different conversion processes. I'm not at all opposed to wider support or more proper approaches.

**Comment by makyen** [comment]
I haven't tested with importing from a network based repository. I do, routinely, edit through the import/export `<textarea>` (sometimes including complete replacement). I've experienced no issues. OTOH, I have not extensively tested.

After a somewhat more testing, what I provided didn't handle entering `&amp;` into the `<textarea>`.

The following does what I'd expect to happen with this functionality. In other words, what's entered in the autoreview `<textarea>` ends up being shown in the autoreview popup and is entered verbatim into the in-page comment `<textarea>`:

    function htmlToMarkDown(html) {
      markdown = html.replace(/<a href="(.+?)">(.+?)<\/a>/g, '[$2]($1)');
      markdown = markdown.replace(/<em>(.+?)<\/em>/g, '*$1*').replace(/<strong>(.+?)<\/strong>/g, '**$1**');
      //Still have HTML entities. Convert them using a <textarea>.
      //Ref: https://stackoverflow.com/a/7394787/
      //Ref: https://stackoverflow.com/a/1395954/
      var textarea = document.createElement('textarea');
      textarea.innerHTML = markdown;
      return textarea.value;
    }

    function markDownToHtml(markdown) {
      html = markdown.replace(/&/g, '&amp;').replace(/\[([^\]]+)\]\((.+?)\)/g, '<a href="$2">$1</a>');
      return html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\*([^`]+?)\*/g, '<em>$1</em>');
    }


Entered into autoreview popup (inline, or import/export): `This is a test of the & emergency -1 < 5 > 4. &amp; &lt; &gt;`

**Comment by oliversalzburg** [comment]
@makyen Could you open a pull request with this change?
