### ISSUE TITLE
Can not save custom entries in Firefox.

### ISSUE THREAD

**Issue by 5chdn** [Benjol/SE-AutoReviewComments#126]
I have a [list of custom comments](https://gist.githubusercontent.com/5chdn/3c9cb4365a523fd53dd3dcb96eca57c3/raw/d01a3fc790ba6ff9447d947e8afb3dc392d4ffda/AutoReviewComments.md). I can import them just fine as markdown, as json or simply copy and pasting it.

However, when I switch the  tab or go to another thread in the same tab or at last after restarting the browser, all my custom comments are gone and I have to import them over and over again. 

Any idea why? How to bypass that issue? Thanks.

**Comment by Benjol** [comment]
Very strange.
The data is stored in localStorage. Maybe you've got some kind of anti-spyware plugin which is a bit too enthusiastic?

**Comment by 5chdn** [comment]
Looked into the storage inspector. It seems my browser deletes localStorage on close. But which category does localStorage belong to?

![screenshot at 2016-09-02 19-54-06](https://cloud.githubusercontent.com/assets/15729797/18213232/7f8fa7f8-7147-11e6-8c8e-19c0ae004315.png)

Is there any way I can define my defaults elsewhere? I don't want to change how my browser deals with history and data in first place.

**Comment by oliversalzburg** [comment]
Offline Website data, I guess

**Comment by 5chdn** [comment]
Well it's obiously related to my browser settings. Keeping Offline Website Data did not do the trick for me.
