### ISSUE TITLE
Not working in Firefox 49.0.2

### ISSUE THREAD

**Issue by abenkovskii** [Benjol/SE-AutoReviewComments#127]
I'm experiencing an issue similar to this: #77. The "auto" link doesn't show up in firefox.
I tried installing the Firefox add-on (version 1.4.1.1-signed.1-signed). I also tried installing the script (version 1.4.2) using gracemonkey (3.9).

**Comment by abenkovskii** [comment]
Update: version 1.4.2 doesn't appear to be working in chromium 54.0.2840.90 either (both as add-in and as tampermonkey extension).

**Comment by abenkovskii** [comment]
Sorry. Turns out I am a moron. I didn't look at the screenshot properly and was looking for the link near the "flag" link. By looking at the source code I figured out that I'm supposed to click "add a comment" and than the "auto" link shows up to the right of the comment box.

**Comment by zixuan75** [comment]
@abenkovskii What are you saying? I don't understand.
