### ISSUE TITLE
Owncloud text file as remote source loads for ever

### ISSUE THREAD

**Issue by krichter722** [Benjol/SE-AutoReviewComments#131]
Specifying an owncloud text file (e.g. https://richtercloud.de:451/index.php/s/aKBncvJnKMzgbDM/download) causes the action after pressing the `get` button to load for ever.

Feel free to use the provided link for investigation, it only contain sensible information.

experienced with 1.4.1.1-signed.1-signed in Firefox 52.0.2 on Ubuntu 16.10

**Comment by kevin-brown** [comment]
It _probably_ has something to do with the fact that the file is being force-downloaded, instead of being rendered as a text file through the browser.

**Comment by krichter722** [comment]
It'd be nice if the add-on would support those fore-downloads as well.

**Comment by oliversalzburg** [comment]
The link is down.
