### ISSUE TITLE
Chat sites should be blacklisted.

### ISSUE THREAD

**Issue by Cerbrus** [Benjol/SE-AutoReviewComments#137]
This userscript shouldn't run on SE's chat sites. To fix, add these excludes:

    
    // @exclude /^https?:\/\/(.*\.)?chat.stackoverflow\.com/.*$/
    // @exclude /^https?:\/\/(.*\.)?chat.stackexchange\.com/.*$/

**Comment by oliversalzburg** [comment]
We have open PR #133, but the contributor, so far, wasn't able to provide a proper patch. A proper PR would be greatly appreciated.

**Comment by Cerbrus** [comment]
Same issue here... what's going on there? o.O

**Comment by oliversalzburg** [comment]
The editor being used changed the line endings of the file. Or it replaces tabs with spaces or something like that.

**Comment by Cerbrus** [comment]
See #138, Created a proper PR.
