### ISSUE TITLE
Update link from MSO to MSE

### ISSUE THREAD

**Issue by episanty** [Benjol/SE-AutoReviewComments#149]
The default comments include a link to MSO in

      ###[A] Nothing but a URL (and isn't spam)
      Whilst this may theoretically answer the question, [it would be preferable](//meta.stackoverflow.com/q/8259) to include the essential parts of the answer here, and provide the link for reference.

which should really be updated to its corresponding MSE version, `https://meta.stackexchange.com/a/8259`.

**Comment by oliversalzburg** [comment]
I'd be happy to merge a pull request with the suggested change.

**Comment by Benjol** [comment]
Fixed in latest release, thanks.
