### ISSUE TITLE
"auto" button appears in wrong spot on sites with responsive design

### ISSUE THREAD

**Issue by gparyani** [Benjol/SE-AutoReviewComments#154]
The "auto" button appears in the wrong spot on sites with responsive design:

![auto wrong place](https://user-images.githubusercontent.com/6440487/45181146-2fa78380-b1e3-11e8-8a12-e64f46d1b4ef.PNG)

...and if the new contributor indicator is visible:

![auto wrong place new contributor](https://user-images.githubusercontent.com/6440487/45181181-48b03480-b1e3-11e8-9835-da9be64b1654.png)

Reproduced in Microsoft Edge.

**Comment by oliversalzburg** [comment]
Nobody is actively maintaining this script. If you need something changed, you're going to want to create a pull request for it. A warning though, there is also no guarantee there will be anyone there to review/merge it, as I definitely won't do it.

Sorry :(

**Comment by gparyani** [comment]
This was fixed at some point, so closing.
