### ISSUE TITLE
How do I restore lost auto comments?

### ISSUE THREAD

**Issue by barmar** [Benjol/SE-AutoReviewComments#160]
I cleared my browser data yesterday, and lost all my personalize auto comments in the process. I have Time Machine backups, so I should be able to restore things from before that, but I haven't been able to do this successfully. I tried restoring just my Cookies file, and also tried restoring the entire ~/Library/Application Support/Chrome/Default directory.

Where were the comments stored, so I can try to resurrect that resource and copy them by hand?

**Comment by oliversalzburg** [comment]
The comments are stored in the browsers LocalStorage. I don't know how they could be retrieved from a cold state.

**Comment by barmar** [comment]
I tried restoring ~/Library/Application Support/Google/Chrome/Default/Local Storage/leveldb from a Time Machine backup, but all the comments reverted back to their defaults.

**Comment by Benjol** [comment]
How about just searching your activity for comments and picking out the most used ones? Painful, but probably would take less time than you've already lost.

-----Original Message-----

**Comment by Benjol** [comment]
Closing as there's not much more we can do about this. Sorry.
