### ISSUE TITLE
Auto link suddenly disappeared today from Chrome 72

### ISSUE THREAD

**Issue by mplungjan** [Benjol/SE-AutoReviewComments#163]
I did not do anything like adblocking or so to change this. Just from one SO question to the next

**Comment by NathanOliver1** [comment]
Same issue here.  Running Chrome Version 72.0.3626.109 (Official Build) (64-bit) on Windows 10 Pro Version 1803.  Comments were working yesterday but are not working today.  It looks like they turned the help link in the comments to a help button so the auto link can't be inserted next to it.

**Comment by mplungjan** [comment]
line 842      var injectNextTo = $("#" + divid).find(".comment-help-link");
Likely should be
      var injectNextTo = $("#" + divid).find(".js-comment-help-link");

**Comment by LunarWatcher** [comment]
The same is also happening in Firefox 65.0.1 (64 bit) with the userscript (using Tampermonkey).

**Comment by machavity** [comment]
I edited my local UserScript and confirmed it works

**Comment by Tyler-H** [comment]
They probably adjusted the class name in one of their many daily builds...

**Comment by mplungjan** [comment]
How to get the chance installed quickly?

**Comment by machavity** [comment]
I'm not sure on the Chrome extension. I use TamperMonkey with FireFox (plugin stopped working with the big Mozilla plugin update last year) so I could edit the underlying JS file directly and get it working. You could always remove the plugin, install TamperMonkey and then install the ARC userscript version, then edit it. A lot of work, though, for what will hopefully get patched quickly.

**Comment by oliversalzburg** [comment]
If someone could open a PR, I'd be happy to merge it and compile a new version of the script later at home.

**Comment by oliversalzburg** [comment]
Oh, that already happened https://github.com/Benjol/SE-AutoReviewComments/pull/164 :D

**Comment by machavity** [comment]
@oliversalzburg If you'll increment the version then the userscript crowd can get the update now. I know the Chrome extension will take longer

**Comment by Benjol** [comment]
Just released fix, v1.4.5

**Comment by barmar** [comment]
I still see 1.4.3 in the Chrome store. Are we waiting for Google to approve it?

**Comment by makyen** [comment]
@barmar The most recent information is [this comment](https://github.com/Benjol/SE-AutoReviewComments/issues/169#issuecomment-466339481) in the issue you opened, #169. As the author of that issue, you should have been notified when the comment was placed (16 hours ago). That comment says:

>Corrected here, but I haven't yet uploaded the new version to the Store. Probably tomorrow.

If you want the functionality immediately, then you will need to switch to using this as a userscript. It should be noted that updates will *always* be faster for the userscript than for the extension, due to the additional overhead of publishing a new extension version.

**Comment by barmar** [comment]
You closed my issue as a duplicate, I thought further comments should be here. And I misunderstood "just released fix" as meaning that you'd uploaded it to the store (I didn't notice that the date was older than when you said "maybe tomorrow").

I'm not trying to rush you, I was just confused about the timeline.

**Comment by Benjol** [comment]
up now
