### ISSUE TITLE
"Auto" link not apperaing anymore

### ISSUE THREAD

**Issue by a-stone-arachnid** [Benjol/SE-AutoReviewComments#167]
Stack Exchange removed the class `.comment-help-link` on the comment help link, so that needs to be updated to `.js-comment-help-link` for it to work.

Using version 1.4.4 on TamperMonkey and Waterfox.

**Comment by dtgriscom** [comment]
Confirmed, and I've just discovered how much I use this tool...

(A belated thanks!)

**Comment by Benjol** [comment]
Duplicate of #163, fix on the way...
