### ISSUE TITLE
Welcome message not inserted

### ISSUE THREAD

**Issue by Glorfindel83** [Benjol/SE-AutoReviewComments#170]
The welcome message is no longer automatically inserted; the 'loader' icon remains visible and the console shows an error:

> TypeError: data.items is undefined[Learn More] first-posts:294:11
> success https://superuser.com/review/first-posts:294 i4jQuery

<img width="721" alt="Screenshot 2019-03-10 at 12 21 09" src="https://user-images.githubusercontent.com/24611142/54084347-ccccab80-432f-11e9-983e-e54eaf04e2d3.png">

- macOS 10.14.3
- Firefox 65.0.1
- Violentmonkey 2.10.1

**Comment by makyen** [comment]
This is highly likely to be a duplicate of #128. If it is, then this will go away for you once the 24 hour SE API period in which you are in rolls over so you have a new allocation of 300 requests without an SE API key (rollover times depend on when your IP was accessing the SE API).

**Comment by Glorfindel83** [comment]
@makyen you're right, it works now after the daily quota reset.
