### ISSUE TITLE
Wrong comment inserted while editing

### ISSUE THREAD

**Issue by oliversalzburg** [Benjol/SE-AutoReviewComments#53]
When editing a comment (by double-clicking it) while it is selected, pressing the Insert button will cause invalid data to be inserted into the target.

**Comment by Benjol** [comment]
@oliversalzburg, motivated? :)

**Comment by oliversalzburg** [comment]
I'll check it out again. But today I have to get some work done ;D

**Comment by Benjol** [comment]
I think we can call this fixed by #92
