### ISSUE TITLE
Can't click "Login with Google" button on sites where I'm not logged in

### ISSUE THREAD

**Issue by Undo1** [Benjol/SE-AutoReviewComments#62]
When the userscript is running, I get this error in the console on pageload, only on sites where I'm not currently logged in:

![screen shot 2014-08-02 at 3 15 05 pm](https://cloud.githubusercontent.com/assets/5162342/3789065/32116536-1a8a-11e4-9f3d-7c4fedf0c026.png)

And I can't click the "Login with Google" button on the modal dialog that shows up when I try to vote. This is occuring on 1.3.3.3 and 1.3.3

**Comment by oliversalzburg** [comment]
I assume this is fixed in 1.4.0. Otherwise please reopen
