### ISSUE TITLE
Add UnTag step to GetRemote URL

### ISSUE THREAD

**Issue by rolfl** [Benjol/SE-AutoReviewComments#78]
I am building a system (see chat room http://chat.stackexchange.com/rooms/20341/stackmonkey ) that will support supplying different comment-sets for different stack sites. The  logical way to do this would be to have a SetStorage for each stack site, but an interim solution would be to do the auto-load of comments, and supply the Stack site $SITEURL$ as part of the remote URL... for example:

    http://path.to.my.server/commentsource/$SITEURL$/comments

By adding UnTag support to the URL in GetRemote you can allow people to be smarter about what their remote source supplies.

**Comment by oliversalzburg** [comment]
LocalStorage is local to the current domain and the user is in control of the URL from which comments are imported. What am I missing here?

**Comment by rolfl** [comment]
Uhm.... apparently you are missing nothing. Thanks, I overlooked that entirely.
