### ISSUE TITLE
Error with the extension in Chromium (Ubuntu 14.04)

### ISSUE THREAD

**Issue by camilstaps** [Benjol/SE-AutoReviewComments#79]
I'm on Chromium 39.0.2171.65 in Ubuntu 14.04 and installed the AutoReviewComments extension from the Chrome webstore.

When I go to any SE page and hit 'add comment', no 'auto' link is added. Instead, I see this in the console:

    Uncaught TypeError: Cannot read property 'replace' of undefined      VM247:524
      (anonymous function)                                               VM247:524
      f.event.dispatch                                                   jquery.min.js:3
      h.handle.i                                                         jquery.min.js:3 

The line that is referred to is the second line here:

    $("#content").delegate(".comments-link", "click", function () {
      var divid = $(this).attr('id').replace('-link', '');
      var posttype = $(this).parents(".question, .answer").attr("class").split(' ')[0]; //slightly fragile

Is it possible to use the extension in Chromium?

If you need more details, shout!

**Comment by oliversalzburg** [comment]
Please try installing the latest build directly: https://github.com/Benjol/SE-AutoReviewComments/releases/tag/v1.3.3.3

**Comment by camilstaps** [comment]
Thanks very much, that resolved it.
