### ISSUE TITLE
StackOverflow layout changes breaking the add on

### ISSUE THREAD

**Issue by miohtama** [Benjol/SE-AutoReviewComments#80]
The stackoverflow.com layout changed recently. 

After installting addon on Firefox I do not get *Auto* link. I assume the layout changes have broken the add-on?

**Comment by oliversalzburg** [comment]
Try the latest build from https://github.com/Benjol/SE-AutoReviewComments/releases/tag/v1.3.3.3

**Comment by ajkuck** [comment]
I was having the same problem with the _Auto_ link not appearing.  After I installed version 1.3.3.3, I now see it when I view stackoverflow.com, but not on any of the other stackexchange.com sites.  

Has anyone else found this to be the case?  (FWIW, I'm using the Firefox addon on Mac OS Mavericks.)

**Comment by oliversalzburg** [comment]
@Benjol What's the current status of publishing the latest version to the official plugin platforms (Chrome Web Store, Mozilla Plugins, ...)?

**Comment by Benjol** [comment]
Oliver,

I'm open to doing anything, but I kind of needed Caleb's help for wrangling
the git branches into shape.

Ben

**Comment by oliversalzburg** [comment]
Ah, I see. Well, it would be cool if we could get the release train going :)

**Comment by miohtama** [comment]
@oliversalzburg The latest build fixes this for me. Should I close the the issue?

**Comment by oliversalzburg** [comment]
@miohtama Great. I'll close it for you :)
