### ISSUE TITLE
"auto" link gets multiplied when putting multiple comments on the same post

### ISSUE THREAD

**Issue by IzzySoft** [Benjol/SE-AutoReviewComments#85]
When adding a comment, the "auto" link gets multiplied:

* on the first comment, it's a single link
* on the second comment, you get two links
* on the third comment, it will be 3 links (see screenshot)
* on th..is place, I've stopped trying :eyes: 

To reproduce: Pick a post (in my case it was an answer) without comments, create the first, then create the next, and so on. Note this does not initially happen when you're e.g. the third to comment – only when you yourself put multiple comments in a row on the same post (e.g. if you've got to split-up your too-long comment).

![Screenshot](http://i.imgur.com/zUZzSpB.png)

Encountered here with the latest (1.4.0) version.

**Comment by oliversalzburg** [comment]
Note to self: The `injectAutoLink*` methods don't properly check if an "auto" link is already inserted.

**Comment by Benjol** [comment]
Closing, fix looks good and is merged to devel
