### ISSUE TITLE
Where did the "Welcome check" go?

### ISSUE THREAD

**Issue by IzzySoft** [Benjol/SE-AutoReviewComments#87]
With 1.4.0 (or was it the update to Firefox-36?), the "welcome check" seems to be gone. Before, the script checked whether the poster of a question/answer was a new user, and if so added the "Welcome message". As it is now, there is no welcome message added anymore. Also, details on the user are no longer displayed on top of the popup.

A little analysis turned out that `getUserId()` seems to be broken: `userlink.length` is always `0`, so we get no userId, so we cannot check whether the user is new. Seems to be trouble with the DOM selector: there is no `el.parents('div')` (length:0, which IMHO means "not found"?). Even more strange is where `el` itself seems to point here: `Object { 0: Window → how-to-store-image-from-camera-into-variable-in-android-programming, length: 1 }` – that's the "page" part of the URL, not the current element.

I think I've fixed that by adjusting line 791:

~~~ .diff
- var userid = getUserId($(this));
+ var userid = getUserId($("#content"));
~~~

I've not thoroughly tested it yet, but it seems to work on questions and answers alike (checked on a few of both). Can anybody confirm?

**EDIT:** My fix only works for answers if there's not more than one (but I've just verified the same issue on my second machine – so it exists on FF36 with Windows and Scriptish as well as with Linux and Greasemonkey). It seems to be the right *place* to fix it (line 791), but not the right fix ("#content").

**EDIT-2:** This one is better – and most likely even the right one:

~~~ .diff
- var userid = getUserId($(this));
+ var userid = getUserId(targetObject);
~~~

Quick test: Works on questions (yes), single answers (yes), multiple answers (yes!). Still, someone else please cross-check :innocent:

**Comment by Benjol** [comment]
This is weird, because I'm sure it worked when I was testing...

**Comment by IzzySoft** [comment]
My guess is it's a change on FF side. They've started some weird "security stuff" lately (try e.g. to `console.log(window.location.href)` to see what I mean – and as `this` now turns up as the window element itself, to me it sounds like it could be related).

**Comment by Benjol** [comment]
@oliversalzburg, I've pulled in @IzzySoft's correction for this, in case you want an easy way to check it on devel. If you're happy, I'll let you close this issue.

**Comment by oliversalzburg** [comment]
Tested devel with Firefox and Chrome Canary on Windows.

**Comment by IzzySoft** [comment]
\o/ :thumbsup: Thanks for testing and integrating!

**Comment by Julian-O** [comment]
May I, ever so politely and respectful of the contributors' time, suggest this bug fix alone warrants another release?

**Comment by Benjol** [comment]
@Julian-O, done.
(@oliversalzburg for info)

**Comment by oliversalzburg** [comment]
@Benjol Good job. Well done! :+1:
