### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by oliversalzburg** [Benjol/SE-AutoReviewComments#93]
I know this has the potential to cause a very long discussion, but we need to have it ;D

We should settle on a code style that we should follow. The current mix of different styles is very confusing.

The major points we need to settle on are:
1. Strings - Single or double quotes?
2. Spaces - Spaces within function call parenthesis? Spaces after comma?

As an example, I've set up https://github.com/oliversalzburg/SE-AutoReviewComments/tree/feature/code-style with our company code style applied to the main parts of the project. The main aspects here are:
1. Double-quotes for strings
2. Spaces inside parenthesis and around operators and delimiters
3. K&R bracing style
4. `if`, `for`, etc enforce opening brace
5. Opening brace enforces newline
6. Main indents are tabs (4 spaces wide), secondary indents are spaces (aka "smart tabs")

**Comment by Benjol** [comment]
I think any style is better than no style (or a mix of styles).

My own preference is for spaces over tabs, and not having spaces inside parenthesis (but having them around operators).

Apart from that, yes.

**Comment by oliversalzburg** [comment]
I got it over with now. Even though it's a ton of changes, it's mostly changes in consistency.

Although I *really* hope I didn't mess up any of the escaped quotes :D
