### ISSUE TITLE
Update installation instructions for Firefox

### ISSUE THREAD

**Issue by krichter722** [Benjol/SE-AutoReviewComments#96]
http://stackapps.com/tags/script/info states "Click on the link to the .user.js file found in the post." (which post -> add a link) clicking on a text file very likely opens a text editor (-> explain). Is this an alternative method to the Firefox add-on or an update (-> mention it)?

**Comment by Benjol** [comment]
I'm assuming you got to that page (http://stackapps.com/tags/script/info) by clicking on a link in the README.
Directly above that link, it says:

> Click [HERE](https://github.com/Benjol/SE-AutoReviewComments/raw/master/autoreviewcomments.user.js) to install the user script

And that is where you should click

**Comment by krichter722** [comment]
> I'm assuming you got to that page (http://stackapps.com/tags/script/info) by clicking on a link in the README.
No.

The issue is not about providing one way to get it right, but making all descriptions consistent.

**Comment by Benjol** [comment]
The problem is that http://stackapps.com/tags/script/info doesn't belong to me, I can't change it, and it is a set of generic instructions for ALL the scripts on StackApps, so it can't refer to a specific link.
